version: '1.0'

services:

  postgres:
    image: postgres:latest
    container_name: t1_java_demo
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=pass

